window.onload=function() {

	var div1=document.createElement("div");
	var sheet1 = document.createElement("style");
	sheet1.innerHTML="#divbar{display:block;text-align: center; position:absolute; overflow:hidden;box-shadow: 1px 5px 1px #050;width:100%;height:50px; padding-right: 10px; padding-left:20px; color:white;font-size:14px;  box-shadow:	0px 1px 3px 0px rgba(0, 0, 0, .3);font-weight: bold;-webkit-animation: bounce 800ms ease-out;-moz-animation: bounce 800ms ease-out;-o-animation: bounce 800ms ease-out;animation: bounce 800ms ease-out; }  @-webkit-keyframes bounce { 0% {-webkit-transform:translateY(-100%);opacity: 0;} 5% {-webkit-transform:translateY(-100%);opacity: 0;} 15% {  	-webkit-transform:translateY(0);padding-bottom: 5px;}30% {-webkit-transform:translateY(-50%);}40%{-webkit-transform:translateY(0%);padding-bottom: 6px;} 50% {-webkit-transform:translateY(-30%);}70% {-webkit-transform:translateY(0%);padding-bottom: 7px;}80%{ 	-webkit-transform:translateY(-15%);}90%{-webkit-transform:translateY(0%);padding-bottom: 8px;}95%{-webkit-transform:translateY(-10%);}97% { -webkit-transform:translateY(0%);padding-bottom: 9px; } 99% { -webkit-transform:translateY(-5%);  }  100% {  	-webkit-transform:translateY(0);  	padding-bottom: 9px;    opacity: 1;  }}  @-moz-keyframes bounce {  0% {	-moz-transform:translateY(-100%);    opacity: 0;  }  5% {  	-moz-transform:translateY(-100%);    opacity: 0;  }  15% {  	-moz-transform:translateY(0);padding-bottom: 5px;}30% {-moz-transform:translateY(-50%);} 40% {-moz-transform:translateY(0%);    padding-bottom: 6px;  }50% {-moz-transform:translateY(-30%);}70% {-moz-transform:translateY(0%);padding-bottom: 7px;}80% {-moz-transform:translateY(-15%); }90% {-moz-transform:translateY(0%);padding-bottom: 8px;}95% {-moz-transform:translateY(-10%);}97% {-moz-transform:translateY(0%);padding-bottom: 9px;} 99% {-moz-transform:translateY(-5%); } 100% {-moz-transform:translateY(0);padding-bottom: 9px; opacity: 1; }}   @keyframes bounce { 0% {transform:translateY(-100%); opacity: 0; }5% {transform:translateY(-100%);opacity: 0;}15% {transform:translateY(0); padding-bottom: 5px; } 30% {transform:translateY(-50%);}40% {transform:translateY(0%);padding-bottom: 6px;} 50% {transform:translateY(-30%); } 70% {  	transform:translateY(0%);    padding-bottom: 7px;  }  80% {  	transform:translateY(-15%);  }  90% {  	transform:translateY(0%);  	padding-bottom: 8px;  }  95% {  	transform:translateY(-7%);  }  97% {  	transform:translateY(0%);  	padding-bottom: 9px;  }  99% {  	transform:translateY(-3%);  }  100% {  	transform:translateY(0);  	padding-bottom: 9px;    opacity: 1;  }}"
	
	document.body.appendChild(div1);


}